import Head from 'next/head';
import Image from 'next/image';
import useSWRFetch from './api/launches';
import Launches from '../components/Launches';

export default function Home() {
  const { data, error, isLoading } = useSWRFetch();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Space-X launches</h1>
        <p>
          The first 10 Space-X launches,{' '}
          <a href="https://api.spacexdata.com/v5/launches/" target="_blank">
            powered by their API
          </a>{' '}
          - {process.env.API_ENDPOINT}
          <br />
          <small>(I changed to the 1st 10 launches as it gave a better data set to showcase)</small>
        </p>
      </header>
      <main className="content__wrapper">
        <Launches data={data} />
      </main>
    </>
  );
}
